import type { ExploreRow } from "@/lib/explore-queries";

/**
 * 30 hardcoded seed generations for the template.
 * These provide a working explore grid out-of-the-box with no database required.
 * Mix of images and videos in various aspect ratios.
 */
export const SEED_GENERATIONS: ExploreRow[] = [
  {
    id: "seed-001",
    user_id: "template",
    prompt: "A cyberpunk cityscape at night with neon lights reflecting off wet streets",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/001.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T10:00:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#1a0e2e",
    blur_data: null,
  },
  {
    id: "seed-002",
    user_id: "template",
    prompt: "A serene Japanese garden with cherry blossoms and a stone bridge",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/002.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:55:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#e8c4d8",
    blur_data: null,
  },
  {
    id: "seed-003",
    user_id: "template",
    prompt: "Portrait of a woman with flowers in her hair, soft lighting",
    aspect_ratio: "3:4",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/003.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:50:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#d4a574",
    blur_data: null,
  },
  {
    id: "seed-004",
    user_id: "template",
    prompt: "An astronaut floating above Earth with the sun rising behind",
    aspect_ratio: "1:1",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/004.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:45:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#0a1628",
    blur_data: null,
  },
  {
    id: "seed-005",
    user_id: "template",
    prompt: "A golden retriever running through autumn leaves in a park",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/005.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:40:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#c88b3a",
    blur_data: null,
  },
  {
    id: "seed-006",
    user_id: "template",
    prompt: "Abstract geometric art in vibrant blues and oranges",
    aspect_ratio: "1:1",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/006.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:35:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#2d5fa0",
    blur_data: null,
  },
  {
    id: "seed-007",
    user_id: "template",
    prompt: "A medieval castle on a cliff overlooking a misty valley",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/007.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:30:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#4a5568",
    blur_data: null,
  },
  {
    id: "seed-008",
    user_id: "template",
    prompt: "Underwater scene with colorful coral reef and tropical fish",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/008.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:25:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#0e4d6e",
    blur_data: null,
  },
  {
    id: "seed-009",
    user_id: "template",
    prompt: "A futuristic sports car driving through a neon tunnel",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/009.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:20:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#1e0a3c",
    blur_data: null,
  },
  {
    id: "seed-010",
    user_id: "template",
    prompt: "A cozy cabin in a snowy forest with warm light from windows",
    aspect_ratio: "4:3",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/010.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:15:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#2d3748",
    blur_data: null,
  },
  {
    id: "seed-011",
    user_id: "template",
    prompt: "A steaming cup of coffee on a rustic wooden table with morning light",
    aspect_ratio: "1:1",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/011.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:10:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#6b4226",
    blur_data: null,
  },
  {
    id: "seed-012",
    user_id: "template",
    prompt: "Northern lights aurora borealis over a frozen lake in Iceland",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/012.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:05:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#0b2e1e",
    blur_data: null,
  },
  {
    id: "seed-013",
    user_id: "template",
    prompt: "A cat sitting on a windowsill watching rain",
    aspect_ratio: "3:4",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/013.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T09:00:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#5a6b7c",
    blur_data: null,
  },
  {
    id: "seed-014",
    user_id: "template",
    prompt: "A dragon flying over a fantasy landscape with waterfalls",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/014.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:55:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#2a4858",
    blur_data: null,
  },
  {
    id: "seed-015",
    user_id: "template",
    prompt: "Minimalist still life with white flowers in a ceramic vase",
    aspect_ratio: "2:3",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/015.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:50:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#e8e0d4",
    blur_data: null,
  },
  {
    id: "seed-016",
    user_id: "template",
    prompt: "A bustling street market in Marrakech with spices and textiles",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/016.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:45:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#c46a2e",
    blur_data: null,
  },
  {
    id: "seed-017",
    user_id: "template",
    prompt: "A pixel art spaceship battle scene with explosions",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/017.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:40:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#0a0a2e",
    blur_data: null,
  },
  {
    id: "seed-018",
    user_id: "template",
    prompt: "A surreal Dali-inspired landscape with melting clocks",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/018.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:35:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#b89858",
    blur_data: null,
  },
  {
    id: "seed-019",
    user_id: "template",
    prompt: "A robot painting on a canvas in an art studio",
    aspect_ratio: "1:1",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/019.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:30:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#4a5060",
    blur_data: null,
  },
  {
    id: "seed-020",
    user_id: "template",
    prompt: "Sunset over the ocean with dramatic cloud formations",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/020.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:25:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#e87040",
    blur_data: null,
  },
  {
    id: "seed-021",
    user_id: "template",
    prompt: "A macro photograph of a dewdrop on a leaf",
    aspect_ratio: "1:1",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/021.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:20:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#2e6b3a",
    blur_data: null,
  },
  {
    id: "seed-022",
    user_id: "template",
    prompt: "A vintage train station with steam and golden hour light",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/022.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:15:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#8a7260",
    blur_data: null,
  },
  {
    id: "seed-023",
    user_id: "template",
    prompt: "An owl perched on a branch in a moonlit forest",
    aspect_ratio: "3:4",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/023.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:10:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#1a2030",
    blur_data: null,
  },
  {
    id: "seed-024",
    user_id: "template",
    prompt: "A colorful hot air balloon festival at sunrise",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/024.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:05:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#f0a860",
    blur_data: null,
  },
  {
    id: "seed-025",
    user_id: "template",
    prompt: "A neon sign reading OPEN in a rainy alleyway",
    aspect_ratio: "9:16",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/025.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T08:00:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#2a1040",
    blur_data: null,
  },
  {
    id: "seed-026",
    user_id: "template",
    prompt: "A mountain landscape with a crystal clear alpine lake",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/026.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T07:55:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#3a6890",
    blur_data: null,
  },
  {
    id: "seed-027",
    user_id: "template",
    prompt: "A cyberpunk samurai with glowing katana",
    aspect_ratio: "3:4",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/027.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T07:50:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#1a0030",
    blur_data: null,
  },
  {
    id: "seed-028",
    user_id: "template",
    prompt: "A field of sunflowers stretching to the horizon",
    aspect_ratio: "16:9",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/028.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T07:45:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#d4a020",
    blur_data: null,
  },
  {
    id: "seed-029",
    user_id: "template",
    prompt: "An ancient library with towering bookshelves and candles",
    aspect_ratio: "9:16",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/029.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T07:40:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#4a3020",
    blur_data: null,
  },
  {
    id: "seed-030",
    user_id: "template",
    prompt: "A bioluminescent deep sea creature in the dark ocean",
    aspect_ratio: "1:1",
    image_url: "https://w1ddfvelthbnqh3k.public.blob.vercel-storage.com/seed/030.png",
    video_url: null,
    mux_playback_id: null,
    mode: "image",
    created_at: "2025-01-15T07:35:00Z",
    user_name: "Template",
    user_avatar: null,
    color: "#0a1830",
    blur_data: null,
  },
];
